### PR TITLE
Add spinner component

### LINKED ISSUE #142: [FEATURE REQUEST] Add spinner option to chameleon-loader
Add an option for a spinning animation to chameleon-loader.

### PR DESCRIPTION
**Pull request by kewalter**
Migrates our existing spinner component.  Closes #142

### CODE REVIEW

**Comment by ryuhhnn** [comment]
Might be worth folding this into the chameleon-loader component and making it a variation of it. What do you think?

**Comment by kewalter** [comment]
@ryuhhnn What is the chameleon-loader component going to be?  

https://github.com/MaritzSTL/chameleon/issues/60

**Comment by kewalter** [comment]
Nevermind, I had the term spinner in my head instead of loader.  One is a circle loading animation, one is the 3 dots.

I added this one since we had a spinner component that gets pulled into the button for the loading state.  I think it'd make sense to have loader and spinner combined and just pass a prop for which animation we want.  That is, if UX wants both.

**Comment by ryuhhnn** [comment]
> I think it'd make sense to have loader and spinner combined and just pass a prop for which animation we want

100% totally on board with this!

**Pull request closed without merging**
