### PR TITLE
adding the label

### PR DESCRIPTION
**Pull request by EPrathe**
Just adds a label to the select component

### CODE REVIEW

**Comment by EPrathe** [comment]
> oh wait wait wait, can you bump a minor version, please??

Of course! just to make sure would I just manual change the version in the package.json from 0.1.1 to 0.1.2 ?

**Comment by nodza** [comment]
Screen Shot 2019-11-14 at 4 05 02 PM

@EPrathe  I noticed that if I have a label it throws off the alignment of the carat. Do you see the same?

**Comment by ryuhhnn** [comment]
@EPrathe minor would actually be 0.1.1 => 0.2.0. Thanks for clarifying!

**Comment by EPrathe** [comment]
> Screen Shot 2019-11-14 at 4 05 02 PM
> 
> @EPrathe I noticed that if I have a label it throws off the alignment of the carat. Do you see the same?

I did not notice that, good catch!

**Comment by EPrathe** [comment]
updates have been made, should hopefully be all good now

**Pull request merged**
