### PR TITLE
Chameleon Date

### PR DESCRIPTION
**Pull request by ryuhhnn**
Here is the first stab at the chameleon date component

Screenshot 2019-11-12 at 23 29 33

Some notes:

`.value` will be "" until the user "touches" the component. If an implementer needs to derive the `.value` from the component, they will need to ensure that `.touched` is set to true. I'm iffy on whether or not this is the best implementation/way to go about that since I know that was an issue for us before.

This component will return the user's *local* date. Although the `.date` value will return the full `Date` object, it shouldn't be used, and really is only used internally. I exposed it just in case, but it might be worth making this a private property.

This design is *not* UX approved, so it is bound to change, but styling won't hold up merging. If this gets merged, I'll open up a follow up ticket to address styling to ensure that it's up to par before `v1.0.0`

Any other feedback is greatly appreciated!

### CODE REVIEW

**Comment by ryuhhnn** [comment]
also, snuck in a quick little change to chameleon-button for this 🙊

**Comment by mandymichel** [comment]
This may be the case in the mtzwc component, also, but can we make it so that clicking the icon will open the calendar (in addition to the textfield)? It feels weird for that not to be the case. Also, if I type in the date and hit enter, I expect the same result as if I clicked on the date (calendar closes). That doesn't happen so I'm unsure if typing in the date works.

**Comment by ryuhhnn** [comment]
> I'm assuming the changes to the bundle files were intentional?

Yeah I'm experimenting with doing storybook builds per PR so that we can send review links to UX

**Comment by tfreiner** [comment]
Looks like you have a merge conflict

**Comment by ryuhhnn** [comment]
Going to go ahead and close this for now for a little more refactoring work and UX feedback

**Pull request closed without merging**
